language: node_js

node_js:
  - "0.10"

env:
  - EXPRESS_VERSION=3.x
  - EXPRESS_VERSION=4.x

before_script: npm install express@$EXPRESS_VERSION

script: npm test

notifications:
  irc:
    channels:
      - "irc.mozilla.org#services-dev"
    use_notice: false
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch} - %{commit}: %{author}): %{message} %{build_url}"
